### ISSUE TITLE
Time select region to stop song

### ISSUE THREAD

**Issue by mapeje** [nikarh/reaper-remote-bandui#1]
First, a big thanks for your excellent solution! This is exactly what our band has been looking for and it works really great. However, when we select a song, it does not stop playing at the end of the region. You could add markers, but better perhaps to time select the region from the web before playing. This way, Reaper can stop at the end of each song.

**Comment by nikarh** [comment]
Hey, nice to see that this project was useful outside of my band :)

This makes sense, although Reaper won't stop if you don't check "Stop Playback at end of loop if repeat is disabled." in preferences. Probably worth mentioning that in the readme.

**Comment by mapeje** [comment]
Thanks for quick feedback and good comment on Reaper settings. 
Again thank for the great work!
