### ISSUE TITLE
Navigation beetween markers 

### ISSUE THREAD

**Issue by saefr** [nikarh/reaper-remote-bandui#5]
And another issue i wanted to talk about, is the navigation itself on the app. One good option to have is being able to navigate beetween markers : lets say you have multiple sections on one song, with markers everywhere. Right now you are only able to begin the song, not navigate in the region itself.

You have an example on the Fancier Remote Web UI that work pretty well, i tried to add it to your interface but its a bit difficult for me
https://www.realinks.net/links/fancier-remote/

Its not super important but i think its a good option to have on your interface, when you want to work on specific song parts or relaunch the song in Live use where you have a marker

**Comment by nikarh** [comment]
Hey, check out this build - https://github.com/nikarh/reaper-remote-bandui/actions/runs/8326713660


It would look roughly like this in the UI. Though it clutters the UI a bit, I think it can be useful during rehearsals when working on some progressive math in the middle of the song :P 

![](https://raw.githubusercontent.com/nikarh/reaper-remote-bandui/2830b61a4af1da685ceda33df72666dfbadc16b4/screenshots/Web%20-%20Control.png)

**Comment by nikarh** [comment]
Merged and released

**Comment by saefr** [comment]
Wow, that was quick too 👍 Thank you very much for your work 🥇 
Sorry didnt have the time to check about it, i'm gonna try this version tomorrow. 
At first glance on your screenshots it works but like you said, it clutters a bit the Ui and make it less readable. 

Some ideas or opinion looking at the screenshots : 
- I dont think its interesting to make all the markers visible for all regions, maybe only for the active region ? 
- The previous and next marker are huge in comparison to the stop/start/pause buttons. With an icon, it should be readable and less bulky.
- When a marker is passed, displaying the text somewhere ?

**Comment by nikarh** [comment]
Hi! You're welcome!

> I dont think its interesting to make all the markers visible for all regions, maybe only for the active region ?

That's doable, yes.
Out of curiosity, if you're ok with that, would it be possible for you to share a screenshot of your project on the device (or on pc just with the respective resolution), so I can see just how cluttered it is 

> The previous and next marker are huge in comparison to the stop/start/pause buttons. With an icon, it should be readable and less bulky.

I wasn't sure where to put them. On a phone they certainly don't fit on the top toolbar, so they would take up a whole horizontal row anyway. Unless I were to make these buttons smaller which would make it harder to hit them with a finger on a phone.

If you have an idea how that can be arranged, a rough sketch would be very helpful :)

> When a marker is passed, displaying the text somewhere ?

As in while playing? This is an interesting one, but again, I have no idea where or how to visually show that, so a sketch would be helpful!

**Comment by saefr** [comment]
> Out of curiosity, if you're ok with that, would it be possible for you to share a screenshot of your project on the device (or on pc just with the respective resolution), so I can see just how cluttered it is

Of course ! For reference, my reaper file :
![Screenshot_20240320_091120](https://github.com/nikarh/reaper-remote-bandui/assets/32266423/332b0550-7f63-4adc-bb40-c43f4d0a22fc)

![Screenshot_20240320_091232](https://github.com/nikarh/reaper-remote-bandui/assets/32266423/da20be20-2924-4e0a-98d6-2cb4eee10e19)

I'm using basically the same project as your Mother Project, but with more tracks and inputs/outputs (4 of each)
I subdivised all the backing tracks to have more controls about each individual audios, and i have two different click and instructions tracks for differents people in the group
I use special markers at the end of each region (its sws extension) to stop and go to the next region automatically. I have regions that need to be stopped after playing, and others that need to continue directly to the next. So i cant control it globally like you did with the new option from februrary pull request :+1: 

And the web ui interface with this project :  (with a test Marker on July song)
![Screenshot_20240320_091639](https://github.com/nikarh/reaper-remote-bandui/assets/32266423/c7ae7bd5-d1d1-4e05-90a9-9557d282edea)

**Comment by saefr** [comment]
> I wasn't sure where to put them. On a phone they certainly don't fit on the top toolbar, so they would take up a whole horizontal row anyway. Unless I were to make these buttons smaller which would make it harder to hit them with a finger on a phone.
> 
> If you have an idea how that can be arranged, a rough sketch would be very helpful :)
> 
> As in while playing? This is an interesting one, but again, I have no idea where or how to visually show that, so a sketch would be helpful!

I'm on the same page, i dont know yet how to build it correctly on the UX side. I'm gonna prepare a drawing or something to see what is possible
By the way the markers are working fine, its great :)

**Comment by saefr** [comment]
So i did some paint ! Here is my idea:  

![Sans titre](https://github.com/nikarh/reaper-remote-bandui/assets/32266423/ab90b86e-1f71-4567-88fb-85fb9e2ac7e8)

- Reducing the "Mix" And "Controls" button, they have little too much height
- Put the "Edit" Button after the last song, its not something you use all the time
- Make The play/pause/top button a little larger and center them, split the two "REC" and "LOOPBACK" buttons to make them smaller and in the corners
- A center information panel with the actual song and the actual marker played
- two buttons on each side, for the next and previous markers / next and previous regions

Let me know if it at your taste :D

**Comment by nikarh** [comment]
Hey, thanks for sharing the screenshots and your ideas! You sure use Reaper to its fullest :)

Overall I would say the suggestions make sense.

Questions regarding the mockup

- How do you see next/prev buttons should work? Do they use global reaper layout of regions and markers, or you expect them to only navigate between regions that are enabled and in the order set via the editor?
- Do you see a usecase for next/prev region buttons, or is it more of an aesthetical choice?
- Is there a need of duplicating currently played region, considering it is highlighted below anyway?
- What is the "Actual Marker"? Just the last marker before the cursor?

**Comment by saefr** [comment]
Far from it, but yeah it's an important part of our new setup :) We also use voice FX automations from the reaper itself
Thanks to you, because without the good interface i will not have been able to make it work 🥇 

- It should only navigate beetween the regions enabled by the interface, so yeah it more a "Go to the next region, in the setlist edited"
- Sometimes you want to pass directly to the next region for pratice use or live shenanigans, but yeah its not as important as play or stop buttons. its like the "Next markers", the "REC" or "Loopback" Buttons, they are useful tools to have but you dont use it all the time. Thats why it should be smaller than the play/pause/stop. It made sense to not add them too
- If you pass like me the 8/9 songs in the playlist, you dont see anymore the song played. But maybe its not useful if the focus of the scrolling list of songs is center to the current song ?
- Last marker hit yes !

**Comment by nikarh** [comment]
Hey, I made a PR based on your suggestions, although with several differences:

1. No next/previous region buttons. If I add them as on your mockup, the toolbar takes 3 rows which seems to be too much. I also tried aligning them on a single row as `[<<][<] name [>][>>]`, but that either leaves no space for the region name, or I have to make the button too small to be comfortable for clicking with finder on a phone.
2. I left the edit button at the top for two reasons:
   - I would like its position to be constant
   - Together with a header it adds a clear visual separation between the toolbar above and the region list

Of course, it's not set in stone, and this can be iterated upon.

Thanks for your suggestions! In my opinion, now it looks and behaves substantially better (`[<]` and `[>]` buttons aren't just bindings to `[` and `]` in Reaper, but navigate to the logical previous and next marker-based on the region sorting and visibility).

The logic in `[<]` and `[>]` buttons now also includes a virtual marker at the beginning of each region (unless there is a real one there), so that pressing `[>]` after the last marker in a song would navigate to the beginning of the next song. This seems pretty intuitive and partially solves the use case of navigating to the prev/next region.


You can find the artifact here in the latest release - https://github.com/nikarh/reaper-remote-bandui/releases/tag/v0.13.0

![Screenshot](https://raw.githubusercontent.com/nikarh/reaper-remote-bandui/fbac5affcbc66f448e90bb353be2d04a944e91d3/screenshots/Web%20-%20Control.png)

**Comment by saefr** [comment]
Thanks for the PR, its seems fantastic ! I'm gonna try monday morning, i'm away of my PC for the moment :) 

The next/previous region are not so important because i can make it work using no marker in the region itself, and putting one marker at the beggining of the next region. The behaviour will be the same !
And i understand your point about the edit button, no problem !

**Comment by nikarh** [comment]
Oh, adding a real marker at the beginning of the region is actually not necessary, the code in this PR that resolves the marker sequence adds a virtual marker in the beginning of each region by itself.
But of course it's up to you.

**Comment by saefr** [comment]
Hi ! Just to let you know i tested it last monday, it worked really fine :) The virtual marker works great, i dont have anything more for the project it behave really nicely for us ! 
Thanks you very much for your time 🥇 
(You really should post it to the Reaper forums, they are really active and they will kill for something like this !)

**Comment by nikarh** [comment]
Hi, happy that it works for you! And thank you for your contribution!

I've never actually used Reaper forums, but will consider this option.
